# Generated by Django 3.1.3 on 2020-11-07 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.URLField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='sale/%Y/%m/%d/')),
                ('discount', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('sale_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
