# Generated by Django 3.1.3 on 2020-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20201108_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
