# Generated by Django 3.1.3 on 2020-11-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_auto_20201108_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.TextField(db_index=True),
        ),
    ]
