# Generated by Django 3.1.3 on 2020-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_auto_20201110_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sale',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
